import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Демо-каталог з дизайн-кіту (ShopProject/DESIGN_SYSTEM.md) — реальні назви й ціни,
// щоб скріни й відео епізодів збігалися з тим, що бачив Богдан у Claude Design.
// Ціни — в копійках (₴ × 100), ніколи float.
const products = [
	{
		slug: "hoodie-it-works-on-my-machine",
		title: "Худі «It works on my machine»",
		category: "Одяг",
		priceUAH: 189_000,
		compareAt: null,
		rating: 4.9,
		badge: "new",
		image: "/products/hoodie-it-works.jpg",
		imageCount: 5,
		description: "Важке худі для тих, хто вирішує баги силою переконання. Щільний фліс, не тягнеться після прання.",
		specs: { Розмір: "S–XL", Матеріал: "60% бавовна / 40% поліестер", Догляд: "машинне прання 30°" },
		stock: 24,
	},
	{
		slug: "tshirt-sudo-sandwich",
		title: "Футболка «sudo make me a sandwich»",
		category: "Одяг",
		priceUAH: 89_000,
		compareAt: null,
		rating: 4.6,
		badge: null,
		image: "/products/tshirt-sudo.jpg",
		imageCount: 4,
		description: "100% бавовна, щільність 180 г/м² — не просвічує і не сідає після першого прання.",
		specs: { Розмір: "S–XXL", Матеріал: "100% бавовна", Щільність: "180 г/м²" },
		stock: 41,
	},
	{
		slug: "mug-console-log-coffee",
		title: "Кружка «console.log(coffee)»",
		category: "Кружки",
		priceUAH: 45_000,
		compareAt: 69_000,
		rating: 4.7,
		badge: "-35%",
		image: "/products/mug-console-log.jpg",
		imageCount: 3,
		description: "Керамічна кружка на 350 мл. Друк не стирається навіть після посудомийки.",
		specs: { "Об'єм": "350 мл", Матеріал: "кераміка", Посудомийка: "так" },
		stock: 33,
	},
	{
		slug: "thermo-mug-git-commit-coffee",
		title: "Термокружка «git commit -m coffee»",
		category: "Кружки",
		priceUAH: 78_000,
		compareAt: null,
		rating: 4.8,
		badge: null,
		image: "/products/thermo-mug-git-commit.jpg",
		imageCount: 4,
		description: "Тримає температуру до 6 годин — вистачить рівно на один затяжний code review.",
		specs: { "Об'єм": "400 мл", Матеріал: "нержавіюча сталь", Утримання_тепла: "6 год" },
		stock: 18,
	},
	{
		slug: "keyboard-nby65-hotswap",
		title: "Клавіатура NBY65 · hot-swap",
		category: "Гаджети",
		priceUAH: 499_000,
		compareAt: 599_000,
		rating: 5.0,
		badge: null,
		image: "/products/keyboard-nby65.jpg",
		imageCount: 6,
		description: "65% розкладка, hot-swap PCB — свічі міняються без паяльника. Топ-продаж каталогу.",
		specs: { Розкладка: "65%", Підключення: "USB-C / BT 5.1", "Hot-swap": "5-pin", Вага: "812 г" },
		stock: 9,
	},
	{
		slug: "keyboard-nby75-alu",
		title: "Клавіатура NBY75 Alu",
		category: "Гаджети",
		priceUAH: 640_000,
		compareAt: null,
		rating: 4.9,
		badge: null,
		image: "/products/keyboard-nby75.jpg",
		imageCount: 6,
		description: "Алюмінієвий корпус, gasket-mount — глухий, приємний звук без додаткової шумоізоляції.",
		specs: { Розкладка: "75%", Корпус: "алюміній, gasket-mount", Підключення: "USB-C / BT 5.1", Вага: "1090 г" },
		stock: 5,
	},
	{
		slug: "nby65-barebone-kit",
		title: "NBY65 Barebone Kit",
		category: "Гаджети",
		priceUAH: 320_000,
		compareAt: null,
		rating: 4.8,
		badge: null,
		image: "/products/nby65-barebone.jpg",
		imageCount: 5,
		description: "PCB + корпус + плата стабілізаторів, без свічів і кейкапів — збери клавіатуру під себе.",
		specs: { Розкладка: "65%", Комплектація: "PCB + корпус + стабілізатори", Hotswap: "так" },
		stock: 12,
	},
	{
		slug: "keycaps-pbt-dracula",
		title: "Кейкапи «PBT Dracula»",
		category: "Гаджети",
		priceUAH: 129_000,
		compareAt: null,
		rating: 4.7,
		badge: null,
		image: "/products/keycaps-dracula.jpg",
		imageCount: 4,
		description: "Дабл-шот PBT — легенди не стираються роками. Повний набір під 65-100%.",
		specs: { Профіль: "OEM", Матеріал: "PBT, дабл-шот", Кількість: "131 кейкап" },
		stock: 27,
	},
	{
		slug: "switches-gateron-brown-70",
		title: "Свічі Gateron Brown ×70",
		category: "Гаджети",
		priceUAH: 89_000,
		compareAt: null,
		rating: 4.6,
		badge: null,
		image: "/products/switches-gateron-brown.jpg",
		imageCount: 3,
		description: "Тактильні свічі середньої гучності — комфортно і в опенспейсі, і на дзвінках.",
		specs: { Тип: "тактильні", Actuation_force: "55g", Кількість: "70 шт" },
		stock: 60,
	},
	{
		slug: "keyboard-case-65",
		title: "Кейс для клавіатури 65%",
		category: "Гаджети",
		priceUAH: 99_000,
		compareAt: null,
		rating: 4.5,
		badge: null,
		image: "/products/keyboard-case-65.jpg",
		imageCount: 3,
		description: "Твердий чохол з EVA-піни, тримає форму, коли клавіатура їде з тобою на конференцію.",
		specs: { Сумісність: "65% клавіатури", Матеріал: "EVA-піна, зовні nylon" },
		stock: 15,
	},
	{
		slug: "lube-it-switch-grease",
		title: "Змазка для свічів «lube it»",
		category: "Гаджети",
		priceUAH: 34_000,
		compareAt: null,
		rating: 4.4,
		badge: null,
		image: "/products/lube-it.jpg",
		imageCount: 3,
		description: "Густа змазка для стрижнів і пружин — прибирає скретч і резонанс без переборки клавіатури.",
		specs: { "Об'єм": "10 мл", Тип: "105g0, густа" },
		stock: 50,
	},
	{
		slug: "sticker-pack-merge-conflict",
		title: "Стікерпак «Merge Conflict»",
		category: "Стікери",
		priceUAH: 19_000,
		compareAt: null,
		rating: 4.8,
		badge: null,
		image: "/products/sticker-merge-conflict.jpg",
		imageCount: 3,
		description: "12 вінілових стікерів, водостійкі — переживають ноутбук, пляшку і дощ.",
		specs: { Кількість: "12 шт", Розмір: "5×5 см", Матеріал: "вініл, водостійкий" },
		stock: 120,
	},
	{
		slug: "pin-404-not-found",
		title: "Пін «404 pin not found»",
		category: "Аксесуари",
		priceUAH: 26_000,
		compareAt: null,
		rating: 4.9,
		badge: "new",
		image: "/products/pin-404.jpg",
		imageCount: 3,
		description: "Емальований пін, метал з посрібленням — не тьмяніє в кишені рюкзака.",
		specs: { Матеріал: "емальований метал", Розмір: "3 см", Кріплення: "метелик" },
		stock: 70,
	},
	{
		slug: "mousepad-xl-dark-mode",
		title: "Килимок XL «dark mode»",
		category: "Аксесуари",
		priceUAH: 69_000,
		compareAt: null,
		rating: 4.7,
		badge: null,
		image: "/products/mousepad-dark-mode.jpg",
		imageCount: 4,
		description: "На весь стіл — клавіатура, миша й трохи кави поміщаються без переїзду на дерево.",
		specs: { Розмір: "900×400 мм", Товщина: "4 мм", Основа: "натуральний каучук" },
		stock: 22,
	},
] as const;

// Приклад з адмінки кіту — чернетка, ще не опублікована. Показує, навіщо взагалі
// status: DRAFT | PUBLISHED у схемі: каталог має показувати лише PUBLISHED.
const draftProduct = {
	slug: "hoodie-dark-mode-only",
	title: "Худі «Dark Mode Only»",
	category: "Одяг",
	priceUAH: 219_000,
	compareAt: null,
	rating: 0,
	badge: null,
	image: "/products/hoodie-dark-mode-only.jpg",
	stock: 0,
	status: "DRAFT" as const,
};

async function main() {
	for (const product of products) {
		await prisma.product.upsert({
			where: { slug: product.slug },
			update: product,
			create: product,
		});
	}

	await prisma.product.upsert({
		where: { slug: draftProduct.slug },
		update: draftProduct,
		create: draftProduct,
	});

	console.log(`Засіяно ${products.length + 1} товарів (${products.length} PUBLISHED + 1 DRAFT).`);
}

main()
	.catch((e) => {
		console.error(e);
		process.exit(1);
	})
	.finally(async () => {
		await prisma.$disconnect();
	});
